Tables:
  - commodityHS
  - Country_ISO
  - Aluminium
  - Antimony
  - Asbestos
  - Barytes
  - Bismuth
  - Cadmium
  - Chromium
  - Coal
  - Cobalt
  - Copper
  - Gold
  - Graphite
  - Iron
  - Lead
  - Lithium
  - Magnesite
  - Magnesium
  - Manganese
  - Mercury
  - Molybdenum
  - Nickel
  - Crude_Oil
  - REE
  - Silver
  - Tin
  - Titanium
  - Tungsten
  - Uranium
  - Zinc
  - Zirconium
  - NG
  - WGI
  - Price

regionslist:
  EU:
    - Austria
    - Belgium
    - Belgium-Luxembourg
    - Bulgaria
    - Croatia
    - Czechia
    - Czechoslovakia
    - Denmark
    - Estonia
    - Finland
    - France
    - Fmr Dem. Rep. of Germany
    - Fmr Fed. Rep. of Germany
    - Germany
    - Greece
    - Hungary
    - Ireland
    - Italy
    - Latvia
    - Lithuania
    - Luxembourg
    - Malta
    - Netherlands
    - Poland
    - Portugal
    - Romania
    - Slovakia
    - Slovenia
    - Spain
    - Sweden

BACIcodes:
  Indium: 811291
  Tantalum: 261590
  Graphite: 250410
  Asbestos: 252400
  Iron: 260111
  Manganese: 260200
  Copper: 260300
  Nickel: 260400
  Aluminium: 260600
  Lead: 260700
  Zinc: 260800
  Chromium: 261000
  Molybdenum: 261310
  Titanium: 261400
  Niobium: 261590
  Coal: 270111
  Coking_Coal: 270112
  Lignite: 270112
  Crude_Oil: 270900
  NG: 271111
  Cobalt: 282200
  REE: 284610
  REE: 284690
  Platinum: 711011
  Cadmium: 810710
  Gallium: 811291
  Barytes: 251110
  Magnesite: 251910
  Gypsum_Anhydrite: 252010
  Feldspar: 252910
  Fluorspar: 252922
  Tin: 260900
  Tungsten: 261100
  Uranium: 261210
  Zircon: 261510
  Vanadium: 261590
  Silver: 261610
  Gold: 710811
  Antimony: 261710
  Tellurium: 280450
  Arsenic: 280480
  Selenium: 280490
  Mercury: 280540
  Germanium: 282560
  Lithium: 283691
  Palladium: 711021
  Rhodium: 711031
  Rhenium: 811291
  Boron: 280450

COMTRADEcodes:
  Indium: 811291
  Tantalum: 261590
  Graphite: 250410
  Asbestos: 252400
  Iron: 260111
  Manganese: 260200
  Copper: 260300
  Nickel: 260400
  Aluminium: 260600
  Lead: 260700
  Zinc: 260800
  Chromium: 261000
  Molybdenum: 261310
  Titanium: 261400
  Niobium: 261590
  Coal: 270111
  Coking_Coal: 270112
  Lignite: 270112
  Crude_Oil: 270900
  NG: 271111
  Cobalt: 282200
  REE: 284610
  REE: 284690
  Platinum: 711011
  Cadmium: 810710
  Gallium: 811291
  Barytes: 251110
  Magnesite: 251910
  Gypsum_Anhydrite: 252010
  Feldspar: 252910
  Fluorspar: 252922
  Tin: 260900
  Tungsten: 261100
  Uranium: 261210
  Zircon: 261510
  Vanadium: 261590
  Silver: 261610
  Gold: 710811
  Antimony: 261710
  Tellurium: 280450
  Arsenic: 280480
  Selenium: 280490
  Mercury: 280540
  Germanium: 282560
  Lithium: 283691
  Palladium: 711021
  Rhodium: 711031
  Rhenium: 811291
  Boron: 280450

Output: "Output.db"
Database: "library.db"
BACI: "BACI.db"
OutputFolder: "Documents/geopolrisk"
